# Generated by Django 4.2.1 on 2023-05-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='domain',
        ),
        migrations.AddField(
            model_name='ilan',
            name='domain',
            field=models.ManyToManyField(to='ilans.domain'),
        ),
    ]
