# Generated by Django 4.2.1 on 2023-05-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0002_domain_remove_ilan_domain_ilan_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resim',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
