# Generated by Django 4.2.1 on 2023-05-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0003_alter_ilan_aktif_alter_resim_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255)),
                ('pozisyon', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ilan',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
