# Generated by Django 4.2.1 on 2023-05-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0004_paketler_alter_ilan_bitis_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='paket',
            field=models.ManyToManyField(to='ilans.paketler'),
        ),
    ]
