# Generated by Django 4.2.1 on 2023-05-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0005_ilan_paket'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='meta_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='meta_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
