# Generated by Django 4.2.1 on 2023-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0006_domain_meta_description_domain_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ilan',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
