# Generated by Django 4.2.1 on 2023-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0007_ilan_meta_description_ilan_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='telefon',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='resim',
            name='resim_url',
            field=models.URLField(unique=True),
        ),
    ]
