# Generated by Django 4.2.1 on 2023-06-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilans', '0008_alter_ilan_telefon_alter_resim_resim_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='ilans.domain')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='ilans.ilan')),
            ],
        ),
    ]
